Repository ItRecode/recordit-server, pull requests merged in 2022-12, with the labels that each got.

#8 [BE-14] 테스트용 내장 redis 적용
  build.gradle
  src/test/java/com/recodeit/server/RecodeItServerApplicationTests.java
  src/test/java/com/recodeit/server/configuration/EmbeddedRedisConfiguration.java
Labels: 🛠 Settings

#9 [BE-15] profile 작성
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 🛠 Settings

#11 [BE-21] RedisConfiguration 생성
  src/main/java/com/recodeit/server/configuration/RedisConfiguration.java
  src/main/resources/application-redis.yml
Labels: ✨ Feature

#14 [BE-51] datasource에 포트번호 환경변수로 분리
  src/main/resources/application-datasource.yml
Labels: 🛠 Settings

#15 [BE-46] 자동 리뷰어 설정
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: 🛠 Settings

#16 [BE-52] 패키지명 수정
  build.gradle
  src/main/java/com/recordit/server/RecodeItServerApplication.java
  src/test/java/com/recordit/server/RecodeItServerApplicationTests.java
  src/test/java/com/recordit/server/configuration/EmbeddedRedisConfiguration.java
Labels: 🛠 Settings

#19 [BE-48] Swagger3.0.0 적용
  build.gradle
  src/main/java/com/recodeit/server/configuration/SwaggerConfiguration.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: ✨ Feature

#20 [BE-53] NAVER Code Conventions 적용
  naver-checkstyle-rules.xml
  naver-checkstyle-suppressions.xml
  naver-intellij-formatter.xml
Labels: 🧑‍🎨 Style

#21 [BE-20] SessionUtil 생성
  src/main/java/com/recodeit/server/exception/NotFoundUserInfoInSessionException.java
  src/main/java/com/recodeit/server/util/SessionUtil.java
  src/test/java/com/recodeit/server/util/SessionUtilTest.java
Labels: ✨ Feature

#23 [BE-8] 회원가입 전처리
  src/main/java/com/recodeit/server/configuration/RedisConfiguration.java
  src/main/java/com/recodeit/server/constant/LoginType.java
  src/main/java/com/recodeit/server/controller/MemberController.java
  src/main/java/com/recodeit/server/domain/BaseEntity.java
  src/main/java/com/recodeit/server/domain/Member.java
  src/main/java/com/recodeit/server/exception/NotFoundUserInfoInSessionException.java
  src/main/java/com/recodeit/server/service/MemberService.java
  src/main/java/com/recodeit/server/service/oauth/GoogleOauthService.java
  src/main/java/com/recodeit/server/service/oauth/KakaoOauthService.java
  src/main/java/com/recodeit/server/service/oauth/OauthService.java
  src/main/java/com/recodeit/server/util/SessionUtil.java
  src/main/resources/application-redis.yml
  src/test/java/com/recodeit/server/util/SessionUtilTest.java
Labels: 🙆🏻‍♂️ Merge Needed, ⬆️Top Issues

#24 [BE-56] application-test.yml에 스웨거 설정과 redis password 설정 추가
  src/test/resources/application-test.yml
Labels: 🐞 Bug

#25 [BE-55] OauthServiceLocator 생성
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/main/java/com/recordit/server/service/oauth/GoogleOauthService.java
  src/main/java/com/recordit/server/service/oauth/KakaoOauthService.java
  src/main/java/com/recordit/server/service/oauth/OauthServiceLocator.java
Labels: 🔨 Refactor, ⬆️Top Issues

#26 [BE-37] 사용자 Entity 설계
  src/main/java/com/recordit/server/domain/Member.java
Labels: 🔨 Refactor, ⬆️Top Issues

#28 [BE-70] pull_request_template 수정
  .github/pull_request_template.md
Labels: 🛠 Settings, ⬆️Top Issues

#29 [BE-59] DB 설계 초안으로 Entity 정의
  src/main/java/com/recordit/server/constant/RefType.java
  src/main/java/com/recordit/server/domain/BaseEntity.java
  src/main/java/com/recordit/server/domain/Comment.java
  src/main/java/com/recordit/server/domain/CommentReport.java
  src/main/java/com/recordit/server/domain/ImageFile.java
  src/main/java/com/recordit/server/domain/Member.java
  src/main/java/com/recordit/server/domain/Record.java
  src/main/java/com/recordit/server/domain/RecordCategory.java
  src/main/java/com/recordit/server/domain/RecordColor.java
  src/main/java/com/recordit/server/domain/RecordIcon.java
  src/main/java/com/recordit/server/domain/RecordReport.java
Labels: ✨ Feature

#30 [BE-67] 기존 API 명세 Swagger로 이전
  src/main/java/com/recordit/server/configuration/SwaggerConfiguration.java
  src/main/java/com/recordit/server/controller/MemberController.java
Labels: ✨ Feature, 🙆🏻‍♂️ Merge Needed, ⬆️Top Issues

#27 [BE-60] GlobalExceptionHandler 생성
  src/main/java/com/recordit/server/constant/LoginType.java
  src/main/java/com/recordit/server/exception/ErrorMessage.java
  src/main/java/com/recordit/server/exception/member/MemberExceptionHandler.java
  src/main/java/com/recordit/server/exception/member/NotEnteredLoginTypeException.java
  src/main/java/com/recordit/server/exception/member/NotFoundUserInfoInSessionException.java
  src/main/java/com/recordit/server/exception/member/NotMatchLoginTypeException.java
  src/main/java/com/recordit/server/service/oauth/OauthServiceLocator.java
  src/main/java/com/recordit/server/util/SessionUtil.java
  src/test/java/com/recordit/server/util/SessionUtilTest.java
Labels: ✨ Feature, 👀 Review Needed, ⬆️Top Issues

#31 [BE-71] 로그인/회원가입 DTO 생성 및 스웨거 적용
  src/main/java/com/recordit/server/configuration/SwaggerConfiguration.java
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/dto/member/LoginRequestDto.java
  src/main/java/com/recordit/server/dto/member/RegisterRequestDto.java
  src/main/java/com/recordit/server/dto/member/RegisterSessionResponseDto.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/resources/application-test.yml
Labels: 📃 Docs, ✨ Feature

#32 [BE-29] 로그인/회원가입 요구사항에 따른 테스트코드 및 기능 구현
  build.gradle
  src/main/java/com/recordit/server/configuration/RedisConfiguration.java
  src/main/java/com/recordit/server/constant/RegisterSessionConstants.java
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/domain/Member.java
  src/main/java/com/recordit/server/dto/member/LoginRequestDto.java
  src/main/java/com/recordit/server/dto/member/RegisterRequestDto.java
  src/main/java/com/recordit/server/exception/member/DuplicateNicknameException.java
  src/main/java/com/recordit/server/exception/member/MemberExceptionHandler.java
  src/main/java/com/recordit/server/exception/member/NotFoundRegisterSessionException.java
  src/main/java/com/recordit/server/exception/redis/RedisExceptionHandler.java
  src/main/java/com/recordit/server/exception/redis/RedisParsingException.java
  src/main/java/com/recordit/server/repository/MemberRepository.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/main/java/com/recordit/server/service/oauth/GoogleOauthService.java
  src/main/java/com/recordit/server/service/oauth/KakaoOauthService.java
  src/main/java/com/recordit/server/service/oauth/OauthService.java
  src/main/java/com/recordit/server/util/RedisManager.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: 🐞 Bug, ✨ Feature, 🔨 Refactor, 🛠 Settings, ✅ Test

#33 [BE-75] GOOGLE, KAKAO Oauth 환경변수 등록
  src/main/resources/application-oauth.yml
Labels: 🙆🏻‍♂️ Merge Needed, 🛠 Settings

#34 [BE-76] JpaAuditing 설정
  src/main/java/com/recordit/server/RecordItServerApplication.java
Labels: 🛠 Settings, ⬆️Top Issues

#37 [BE-74] KakaoOauthService 구현
  src/main/java/com/recordit/server/service/oauth/KakaoOauthService.java
  src/test/java/com/recordit/server/service/oauth/KakaoOauthServiceTest.java
Labels: ✨ Feature, ⬇Sub Issues

#36 [BE-73] GoogleOauthService 구현
  src/main/java/com/recordit/server/service/oauth/GoogleOauthService.java
  src/test/java/com/recordit/server/service/oauth/GoogleOauthServiceTest.java
Labels: ✨ Feature, ⬇Sub Issues

#38 [BE-77] 카테고리 API 명세
  src/main/java/com/recordit/server/controller/RecordCategoryController.java
  src/main/java/com/recordit/server/dto/record/category/RecordCategoryResponseDto.java
  src/main/java/com/recordit/server/repository/RecordCategoryRepository.java
  src/main/java/com/recordit/server/service/RecordCategoryService.java
Labels: 📃 Docs, 🙆🏻‍♂️ Merge Needed, ⬆️Top Issues

#35 [BE-72] OauthService 구현체 및 테스트 코드 작성
  build.gradle
  src/main/java/com/recordit/server/RecordItServerApplication.java
  src/main/java/com/recordit/server/constant/OauthConstants.java
  src/main/java/com/recordit/server/dto/member/GoogleAccessTokenResponseDto.java
  src/main/java/com/recordit/server/dto/member/GoogleUserInfoResponseDto.java
  src/main/java/com/recordit/server/dto/member/KakaoAccessTokenResponseDto.java
  src/main/java/com/recordit/server/dto/member/KakaoUserInfoResponseDto.java
  src/main/java/com/recordit/server/environment/GoogleOauthProperties.java
  src/main/java/com/recordit/server/environment/KakaoOauthProperties.java
  src/main/java/com/recordit/server/exception/member/MemberExceptionHandler.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/main/java/com/recordit/server/service/oauth/GoogleOauthService.java
  src/main/java/com/recordit/server/service/oauth/KakaoOauthService.java
  src/main/java/com/recordit/server/service/oauth/OauthService.java
  src/main/java/com/recordit/server/util/CustomObjectMapper.java
  src/main/resources/application-oauth.yml
  src/test/java/com/recordit/server/service/MemberServiceTest.java
  src/test/java/com/recordit/server/service/oauth/GoogleOauthServiceTest.java
  src/test/java/com/recordit/server/service/oauth/KakaoOauthServiceTest.java
  src/test/java/com/recordit/server/util/CustomObjectMapperTest.java
Labels: ✨ Feature, 🛠 Settings, ⬆️Top Issues

#39 [BE-44] 레코드 API 명세
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/RecordDetailResponseDto.java
  src/main/java/com/recordit/server/dto/record/WriteRecordRequestDto.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 📃 Docs, ⬆️Top Issues

#40 [BE-82] 테스트 환경에 oauth 관련 환경변수 추가
  src/test/resources/application-test.yml
Labels: 🐞 Bug, 🙆🏻‍♂️ Merge Needed, 🛠 Settings

#41 [BE-81] 댓글 API 명세
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/controller/RecordCategoryController.java
  src/main/java/com/recordit/server/dto/comment/CommentDto.java
  src/main/java/com/recordit/server/dto/comment/CommentRequestDto.java
  src/main/java/com/recordit/server/dto/comment/CommentResponseDto.java
  src/main/java/com/recordit/server/dto/comment/WriteCommentRequestDto.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/service/CommentService.java
Labels: 📃 Docs, ⬆️Top Issues

#42 [BE-86] color, icon sql 파일 생성
  schema/color.sql
  schema/icon.sql
Labels: ✨ Feature, ⬆️Top Issues

#43 [BE-85] S3 버킷 연결 및 업로드 코드 작성
  build.gradle
  src/main/java/com/recordit/server/configuration/S3Configuration.java
  src/main/java/com/recordit/server/environment/S3Properties.java
  src/main/java/com/recordit/server/exception/file/FileExceptionHandler.java
  src/main/java/com/recordit/server/exception/file/FileInputStreamException.java
  src/main/java/com/recordit/server/util/S3Uploader.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
  src/test/java/com/recordit/server/util/S3UploaderTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feature, 🛠 Settings, ⬇Sub Issues

#44 [BE-87] 개발용 CORS 개방
  src/main/java/com/recordit/server/configuration/WebMvcConfiguration.java
Labels: 🐞 Bug, 🙆🏻‍♂️ Merge Needed

#45 [BE-85] S3 버킷 연결 및 업로드 코드 작성
  src/main/java/com/recordit/server/util/S3Uploader.java
Labels: ✨ Feature, 🙆🏻‍♂️ Merge Needed

#48 [BE-90] ImageFile Entity 등록IP, 다운로드횟수 컬럼 삭제
  src/main/java/com/recordit/server/domain/ImageFile.java
Labels: 🔨 Refactor

#46 [BE-84] 레코드 작성, 레코드 조회 테스트
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✅ Test, ⬆️Top Issues

#47 [BE-30] 레코드 작성, 레코드 조회
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/domain/Record.java
  src/main/java/com/recordit/server/dto/record/RecordDetailResponseDto.java
  src/main/java/com/recordit/server/dto/record/WriteRecordRequestDto.java
  src/main/java/com/recordit/server/dto/record/WriteRecordResponseDto.java
  src/main/java/com/recordit/server/exception/member/MemberNotFoundException.java
  src/main/java/com/recordit/server/exception/record/RecordColorNotFoundException.java
  src/main/java/com/recordit/server/exception/record/RecordExceptionHandler.java
  src/main/java/com/recordit/server/exception/record/RecordIconNotFoundException.java
  src/main/java/com/recordit/server/exception/record/RecordNotFoundException.java
  src/main/java/com/recordit/server/exception/record/category/RecordCategoryNotFoundException.java
  src/main/java/com/recordit/server/repository/ImageFileRepository.java
  src/main/java/com/recordit/server/repository/RecordColorRepository.java
  src/main/java/com/recordit/server/repository/RecordIconRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
Labels: ✨ Feature, ⬆️Top Issues

#49 [BE-92] 레코드 작성, 레코드 조회 테스트 수정
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🐞 Bug, ✅ Test, ⬆️Top Issues

#50 [BE-91] GlobalExceptionHandler에 Validation 예외 추가
  src/main/java/com/recordit/server/exception/GlobalExceptionHandler.java
Labels: ✨ Feature, ⬆️Top Issues

#51 [BE-93] ImageFile Entity 유니크키 제거 및 인덱스 설정
  src/main/java/com/recordit/server/domain/ImageFile.java
Labels: 🔨 Refactor

#54 [BE-94] S3 버킷에 파일 삭제 코드 작성
  src/main/java/com/recordit/server/util/S3Uploader.java
Labels: ✨ Feature

#52 [BE-22] 로깅 설정
  .gitignore
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/log4j2-dev.xml
  src/main/resources/log4j2-local.xml
Labels: ✨ Feature, 🛠 Settings, ⬆️Top Issues

#55 [BE-83] fix: regex nickname 2-10에서 2-8글자로 수정
  src/main/java/com/recordit/server/dto/member/RegisterRequestDto.java
Labels: 🐞 Bug, ⬆️Top Issues

#56 [BE-89] 이미지 파일 로직 ImageFileService 작성
  src/main/java/com/recordit/server/event/S3ImageRollbackEvent.java
  src/main/java/com/recordit/server/exception/file/EmptyFileException.java
  src/main/java/com/recordit/server/exception/file/FileContentTypeNotAllowedException.java
  src/main/java/com/recordit/server/exception/file/FileExceptionHandler.java
  src/main/java/com/recordit/server/service/ImageFileService.java
  src/test/java/com/recordit/server/service/ImageFileServiceTest.java
Labels: ✨ Feature, ✅ Test

#58 [BE-95] 레코드 카테고리 전체 조회
  src/main/java/com/recordit/server/controller/RecordCategoryController.java
  src/main/java/com/recordit/server/domain/RecordCategory.java
  src/main/java/com/recordit/server/dto/record/category/RecordCategoryResponseDto.java
  src/main/java/com/recordit/server/repository/RecordCategoryRepository.java
  src/main/java/com/recordit/server/service/RecordCategoryService.java
  src/test/java/com/recordit/server/service/RecordCategoryServiceTest.java
Labels: 📃 Docs, ✨ Feature, ✅ Test

#59 [BE-96] FE요청으로 인해 닉네임 중복 API 응답값 설정
  src/main/java/com/recordit/server/controller/MemberController.java
Labels: 🙆🏻‍♂️ Merge Needed, 🔨 Refactor

#57 [BE-83] nickname regex '[가-힣A-z0-9]{2,8}로 수정
  src/main/java/com/recordit/server/dto/member/RegisterRequestDto.java
Labels: 🐞 Bug, ⬆️Top Issues

#60 [BE-99] 카테고리 SQL 파일 생성
  schema/category.sql
Labels: 📃 Docs, ✨ Feature, 🛠 Settings

#61 [BE-100] redis cache config 생성
  src/main/java/com/recordit/server/configuration/CacheConfiguration.java
Labels: ✨ Feature
