Repository ItRecode/recordit-server, pull requests merged in 2023-02, with the labels that each got.

#142 [BE-193] 랜덤으로 레코드 조회
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/RandomRecordRequestDto.java
  src/main/java/com/recordit/server/dto/record/RandomRecordResponseDto.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature, ✅ Test

#143 [BE-194] 추억레코드에서 대댓글은 안보이도록 변경
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🔨 Refactor

#146 version 0.1.1 배포
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/RandomRecordRequestDto.java
  src/main/java/com/recordit/server/dto/record/RandomRecordResponseDto.java
  src/main/java/com/recordit/server/dto/record/mix/MixRecordDto.java
  src/main/java/com/recordit/server/dto/record/mix/MixRecordResponseDto.java
  src/main/java/com/recordit/server/exception/record/FixRecordNotExistException.java
  src/main/java/com/recordit/server/exception/record/RecordExceptionHandler.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🎁 Delivery

#147 [BE-197] 0.1.0에서 0.1.1으로 버전 업
  build.gradle
Labels: 📃 Docs

#148 [BE-202] 랜덤 레코드 Swagger Description 수정
  src/main/java/com/recordit/server/dto/record/RandomRecordRequestDto.java
Labels: 🐞 Bug, 📃 Docs

#150 [BE-203] getRandomRecord에서 Transactional readonly 속성 부여
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🐞 Bug, 🔨 Refactor

#149 [BE-199] 모아보기 최신레코드
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/RecentRecordRequestDto.java
  src/main/java/com/recordit/server/dto/record/RecentRecordResponseDto.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature, ✅ Test

#151 [BE-195] 카테고리 조회 로직에서 부모 id를 통해 조회하도록 수정
  src/main/java/com/recordit/server/controller/RecordCategoryController.java
  src/main/java/com/recordit/server/dto/record/category/RecordCategoryResponseDto.java
  src/main/java/com/recordit/server/repository/RecordCategoryRepository.java
  src/main/java/com/recordit/server/service/RecordCategoryService.java
  src/test/java/com/recordit/server/service/RecordCategoryServiceTest.java
Labels: 📃 Docs, ✨ Feature, 🔨 Refactor, ✅ Test

#153 [BE-206] fix: 최신 레코드 조회 테스트 코드 수정
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🐞 Bug, ✅ Test

#154 [BE-205] 랜덤 레코드 조회 시 카테고리 조회 휴면에러 수정
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🐞 Bug

#155 [BE-205] 랜덤 레코드 조회 시 카테고리 조회 휴면에러 수정
  build.gradle
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🐞 Bug

#152 [BE-198] 검색으로 레코드를 조회하는 API 개발
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/RecordBySearchDto.java
  src/main/java/com/recordit/server/dto/record/RecordBySearchRequestDto.java
  src/main/java/com/recordit/server/dto/record/RecordBySearchResponseDto.java
  src/main/java/com/recordit/server/exception/GlobalExceptionHandler.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#156 [BE-208] 추억레코드 응답 값 중 iconColor를 colorName으로 변경
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordResponseDto.java
Labels: 🧑‍🎨 Style

#157 [BE-209] 최신 레코드 조회 시 requestDto에 시간 값 추가
  src/main/java/com/recordit/server/dto/record/RecentRecordRequestDto.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🔨 Refactor

#158 [BE-201] 레코드 쓴 날짜 반환
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/WrittenRecordDayRequestDto.java
  src/main/java/com/recordit/server/dto/record/WrittenRecordDayResponseDto.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/main/java/com/recordit/server/util/DateTimeUtil.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature, ✅ Test

#159 [BE-210] 회원의 닉네임을 변경하는 API 개발
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/domain/Member.java
  src/main/java/com/recordit/server/dto/member/ModifyMemberRequestDto.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: ✨ Feature

#160 [BE-200] 랭킹 시스템 구현
  src/main/java/com/recordit/server/configuration/WebMvcConfiguration.java
  src/main/java/com/recordit/server/constant/RankingPeriod.java
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/converter/RankingPeriodConverter.java
  src/main/java/com/recordit/server/domain/Record.java
  src/main/java/com/recordit/server/domain/RecordCategory.java
  src/main/java/com/recordit/server/dto/record/ranking/RecordRankingDto.java
  src/main/java/com/recordit/server/dto/record/ranking/RecordRankingRequestDto.java
  src/main/java/com/recordit/server/dto/record/ranking/RecordRankingResponseDto.java
  src/main/java/com/recordit/server/exception/record/NotMatchRankingPeriodException.java
  src/main/java/com/recordit/server/exception/record/RecordExceptionHandler.java
  src/main/java/com/recordit/server/repository/RecordCategoryRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/scheduler/RecordRankingScheduler.java
  src/main/java/com/recordit/server/service/RecordRankingProvider.java
  src/main/java/com/recordit/server/service/RecordRankingService.java
  src/main/java/com/recordit/server/util/DateTimeUtil.java
Labels: 📃 Docs, ✨ Feature

#161 [BE-215] 레코드 랭킹 조회시 상위 카테고리를 통해 조회할 경우 하위 카테고리가 포함되지 않는 버그 픽스
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordRankingService.java
Labels: 🐞 Bug

#162 [BE-212] 테스트서버 CI/CD를 위한 github Actions yml파일 작성
  .github/workflows/deploy-dev.yml
Labels: 🛠 Settings

#163 [BE-213] chore : 상용서버 CI/CD를 위한 github Actions yml파일 작성
  .github/workflows/deploy-prod.yml
Labels: 🛠 Settings

#165 [BE-216] 전체 레코드 수 반환 기능 구현
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature, ✅ Test

#167 [BE-218] 0.1.1에서 0.1.2으로 버전 업
  build.gradle
Labels: 📃 Docs

#169 [BE-219] Slack notification 수정
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
Labels: 🐞 Bug, 🛠 Settings

#171 [BE-220] 마이레코드 최신 단 건만 반환하도록 수정
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/RecentOneRecordResponseDto.java
  src/main/java/com/recordit/server/dto/record/RecordByDateDto.java
  src/main/java/com/recordit/server/dto/record/RecordByDateResponseDto.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🔨 Refactor

#172 [BE-228] fix: 마이레코드 단건조회 limit 적용
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🐞 Bug

#173 [BE-229] github actions 환경변수 변경 및 알림 커밋메세지 알림 수정
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
Labels: 🐞 Bug

#164 [BE-211] 내 댓글 관리기능의 내가 작성한 댓글을 조회하는 API 개발
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/dto/comment/MyCommentDto.java
  src/main/java/com/recordit/server/dto/comment/MyCommentRequestDto.java
  src/main/java/com/recordit/server/dto/comment/MyCommentResponseDto.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#170 [BE-225] 로그아웃 기능 개발
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test
