Repository ItRecode/recordit-server, pull requests merged in 2023-03, with the labels that each got.

#174 [BE-230] refactor: 추억레코드 날짜 선택도 가능하도록 변경
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordCommentDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordRequestDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordResponseDto.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#175 [BE-231] chore: develop로 PR시 테스트하는 github actions 작성
  .github/workflows/test_on_pr_to_dev.yml
Labels: 🛠 Settings

#179 [BE-211] 내 댓글 기능에서 반환 값 변경으로 인한 수정
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/dto/comment/MyCommentDto.java
  src/main/java/com/recordit/server/dto/comment/MyCommentResponseDto.java
  src/main/java/com/recordit/server/dto/comment/MyCommentsDto.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#180 [BE-233] 닉네임 변경 시 중복된다면 예외 처리
  src/main/java/com/recordit/server/service/MemberService.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: 🐞 Bug

#182 [BE-234] 레코드 랭킹 조회시 랭킹 집계 시각도 반환하도록 변경
  src/main/java/com/recordit/server/dto/record/ranking/RecordRankingResponseDto.java
  src/main/java/com/recordit/server/exception/record/RecordExceptionHandler.java
  src/main/java/com/recordit/server/service/RecordRankingService.java
Labels: 🔨 Refactor

#183 [BE-214] 0.1.2에서 0.1.3으로 버전 업
  build.gradle
Labels: 📃 Docs

#184 version 0.1.3 배포
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/test_on_pr_to_dev.yml
  build.gradle
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/comment/MyCommentDto.java
  src/main/java/com/recordit/server/dto/comment/MyCommentRequestDto.java
  src/main/java/com/recordit/server/dto/comment/MyCommentResponseDto.java
  src/main/java/com/recordit/server/dto/comment/MyCommentsDto.java
  src/main/java/com/recordit/server/dto/record/RecentOneRecordResponseDto.java
  src/main/java/com/recordit/server/dto/record/RecordByDateDto.java
  src/main/java/com/recordit/server/dto/record/RecordByDateResponseDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordCommentDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordRequestDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordResponseDto.java
  src/main/java/com/recordit/server/dto/record/ranking/RecordRankingResponseDto.java
  src/main/java/com/recordit/server/exception/record/RecordExceptionHandler.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/main/java/com/recordit/server/service/RecordRankingService.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🎁 Delivery

#186 [BE-236] dockerfile에 ARG 수정
  dockerfile
Labels: 🐞 Bug

#176 [BE-227] 회원탈퇴 API와 회원탈퇴기록 관련 스케줄러 기능 개발
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/domain/MemberDeleteHistory.java
  src/main/java/com/recordit/server/exception/member/MemberExceptionHandler.java
  src/main/java/com/recordit/server/exception/member/SignupCooldownException.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/repository/MemberDeleteHistoryRepository.java
  src/main/java/com/recordit/server/repository/MemberRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/scheduler/MemberDeleteHistoryScheduler.java
  src/main/java/com/recordit/server/service/MemberDeleteHistoryService.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: ✨ Feature, ✅ Test

#188 [BE-238] 0.1.3에서 0.1.4로 버전 업
  build.gradle
Labels: 📃 Docs

#189 version 0.1.4 배포
  build.gradle
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/domain/MemberDeleteHistory.java
  src/main/java/com/recordit/server/exception/member/MemberExceptionHandler.java
  src/main/java/com/recordit/server/exception/member/SignupCooldownException.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/repository/ImageFileRepository.java
  src/main/java/com/recordit/server/repository/MemberDeleteHistoryRepository.java
  src/main/java/com/recordit/server/repository/MemberRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/scheduler/MemberDeleteHistoryScheduler.java
  src/main/java/com/recordit/server/service/ImageFileService.java
  src/main/java/com/recordit/server/service/MemberDeleteHistoryService.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: 🎁 Delivery
