Repository ItRecode/recordit-server, pull requests merged in 2023-01, with the labels that each got.

#62 [BE-98] 전체 카테고리 조회 쿼리 수정
  src/main/java/com/recordit/server/dto/record/category/RecordCategoryResponseDto.java
  src/main/java/com/recordit/server/repository/RecordCategoryRepository.java
  src/main/java/com/recordit/server/service/RecordCategoryService.java
  src/test/java/com/recordit/server/service/RecordCategoryServiceTest.java
Labels: 🐞 Bug

#63 [BE-103] LoginType을 PathVariable로 받을 때 Enum으로 받도록 리팩토링
  src/main/java/com/recordit/server/configuration/WebMvcConfiguration.java
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/converter/LoginTypeConverter.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/main/java/com/recordit/server/service/oauth/OauthServiceLocator.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#64 [BE-101] feat: 전체 카테고리 조회 캐시 적용
  src/main/java/com/recordit/server/service/RecordCategoryService.java
Labels: ✨ Feature

#65 [BE-97] 로깅 정책 작성 및 코드에 적용
  src/main/java/com/recordit/server/exception/member/MemberExceptionHandler.java
  src/main/java/com/recordit/server/logger/HTTPLogFilter.java
  src/main/java/com/recordit/server/logger/MDCLoggingFilter.java
  src/main/java/com/recordit/server/service/ImageFileService.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/main/java/com/recordit/server/service/oauth/GoogleOauthService.java
  src/main/java/com/recordit/server/service/oauth/KakaoOauthService.java
  src/main/resources/log4j2-dev.xml
  src/main/resources/log4j2-local.xml
Labels: ✨ Feature, 🔨 Refactor, 🛠 Settings

#66 [BE-104] feat: 세션 set-cookie SameSite None으로 변경
  src/main/java/com/recordit/server/configuration/WebMvcConfiguration.java
Labels: 🐞 Bug, ✨ Feature

#67 [BE-105] 전체 카테고리 조회시 조회 순서 지정
  src/main/java/com/recordit/server/service/RecordCategoryService.java
  src/test/java/com/recordit/server/service/RecordCategoryServiceTest.java
Labels: 🐞 Bug, 🔨 Refactor

#68 [BE-104] fix: Cookie config Bean 삭제 후 yml로 설정
  src/main/java/com/recordit/server/configuration/WebMvcConfiguration.java
  src/main/resources/application-dev.yml
Labels: 🐞 Bug

#70 [BE-109] fix: 로그 ResponseBody에 UTF-8 설정
  src/main/java/com/recordit/server/logger/HTTPLogFilter.java
Labels: 🐞 Bug

#72 [BE-123] 글 작성 시 세션 정보 이용하여 글 작성자를 닉네임으로 설정
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🐞 Bug, ⬆️Top Issues

#73 [BE-125] 닉네임 중복 체크 API 응답값을 "닉네임 중복시 true로 반환"하게 바꾸기
  src/main/java/com/recordit/server/controller/MemberController.java
Labels: 🐞 Bug, 🙆🏻‍♂️ Merge Needed

#74 [BE-133] 저장된 세션 Serializer 때문에 Member ID 안보이는 버그 해결
  src/main/java/com/recordit/server/configuration/RedisConfiguration.java
Labels: 🐞 Bug

#75 [BE-134] EnableCaching 어노테이션 누락 버그
  src/main/java/com/recordit/server/RecordItServerApplication.java
Labels: 🐞 Bug

#78 [BE-124] 로그인 판별 API
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/exception/member/MemberExceptionHandler.java
  src/main/java/com/recordit/server/exception/member/SessionAuthenticationException.java
  src/main/java/com/recordit/server/util/SessionUtil.java
Labels: ✨ Feature, 🔨 Refactor

#79 [BE-135] Session Serializer 타입 에러 수정
  src/main/java/com/recordit/server/util/SessionUtil.java
Labels: 🐞 Bug, 🙆🏻‍♂️ Merge Needed

#80 [BE-136] ImageFileService에 이미지 파일 저장 부분 리팩토링
  src/main/java/com/recordit/server/service/ImageFileService.java
Labels: 🔨 Refactor

#81 [BE-137] swagger endpoint명에 /api 추가
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🙆🏻‍♂️ Merge Needed, ⬆️Top Issues

#82 [BE-132] log에 Swagger 접속 로그 제거
  src/main/java/com/recordit/server/logger/HTTPLogFilter.java
Labels: 🐞 Bug

#83 [BE-138] 레코드, 댓글에 이미지 파일 저장 개수 Column을 제거
  src/main/java/com/recordit/server/domain/Comment.java
  src/main/java/com/recordit/server/domain/Record.java
  src/test/java/com/recordit/server/util/SessionUtilTest.java
Labels: 🐞 Bug, 🔨 Refactor

#84 [BE-138] Record Entity에 이미지 개수 column제거에 따라 record of 파라미터 변경
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🐞 Bug

#85 [BE-142] fix: SessionUtil findUserIdBySession 메서드에서 id값 Long으로 형변환
  src/main/java/com/recordit/server/util/SessionUtil.java
Labels: 🐞 Bug

#77 [BE-121] 레코드 작성, 조회시 이미지가 DB에 반영되는 기능 추가
  src/main/java/com/recordit/server/repository/ImageFileRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
Labels: ✨ Feature

#86 [BE-141] ImageFileService에 저장 부분 리팩토링 및 URL 조회 기능 추가
  src/main/java/com/recordit/server/constant/ImageFileExtension.java
  src/main/java/com/recordit/server/exception/file/FileExceptionHandler.java
  src/main/java/com/recordit/server/exception/file/FileExtensionNotAllowedException.java
  src/main/java/com/recordit/server/repository/ImageFileRepository.java
  src/main/java/com/recordit/server/service/ImageFileService.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/ImageFileServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#87 [BE-143] SessionUtil findUserIdBySession 메서드 NullPointException 버그 fix
  src/main/java/com/recordit/server/util/SessionUtil.java
Labels: 🐞 Bug

#88 [BE-144] 레코드 작성 Happy case test 실패 버그 수정
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🐞 Bug

#89 [BE-139] 상용 환경 구성을 위한 yml 생성
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/log4j2-prod.xml
Labels: ✨ Feature, 🛠 Settings

#90 [BE-128] 댓글 추가
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/domain/Comment.java
  src/main/java/com/recordit/server/dto/comment/WriteCommentRequestDto.java
  src/main/java/com/recordit/server/dto/comment/WriteCommentResponseDto.java
  src/main/java/com/recordit/server/exception/comment/CommentExceptionHandler.java
  src/main/java/com/recordit/server/exception/comment/CommentNotFoundException.java
  src/main/java/com/recordit/server/exception/comment/EmptyContentException.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: ✨ Feature, ✅ Test

#92 [BE-113] 로그 파일 외부로 전송 및 관리
  .gitignore
  build.gradle
  dockerfile
Labels: 🛠 Settings

#94 [BE-151] log xml파일 log4j2 폴더로 이동
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/log4j2/log4j2-dev.xml
  src/main/resources/log4j2/log4j2-local.xml
  src/main/resources/log4j2/log4j2-prod.xml
Labels: 🔨 Refactor, 🛠 Settings

#93 [BE-154] 로그인 판별 API endpoint명을 /auth로 변경하고 회원의 닉네임 반환하도록 수정
  src/main/java/com/recordit/server/controller/MemberController.java
  src/main/java/com/recordit/server/exception/member/MemberExceptionHandler.java
  src/main/java/com/recordit/server/exception/member/SessionAuthenticationException.java
  src/main/java/com/recordit/server/service/MemberService.java
  src/main/java/com/recordit/server/util/SessionUtil.java
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: 🔨 Refactor, 👀 Review Needed, ✅ Test, ⬆️Top Issues

#95 [BE-156] 레코드 조회 시 이미지 리스트 객체를 이뮤터블에서 뮤터블로 변경
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🐞 Bug

#96 [BE-154] 로그인된 회원 닉네임 반환 메서드 테스트코드 수정
  src/test/java/com/recordit/server/service/MemberServiceTest.java
Labels: 🐞 Bug, ✅ Test

#97 [BE-149] DTO 스네이크 케이스에서 카멜 케이스로 변경
  src/main/java/com/recordit/server/dto/comment/CommentDto.java
  src/main/java/com/recordit/server/dto/comment/CommentRequestDto.java
  src/main/java/com/recordit/server/dto/comment/CommentResponseDto.java
  src/main/java/com/recordit/server/dto/comment/WriteCommentRequestDto.java
  src/main/java/com/recordit/server/dto/comment/WriteCommentResponseDto.java
  src/main/java/com/recordit/server/dto/member/GoogleAccessTokenResponseDto.java
  src/main/java/com/recordit/server/dto/member/GoogleUserInfoResponseDto.java
  src/main/java/com/recordit/server/dto/member/KakaoAccessTokenResponseDto.java
  src/main/java/com/recordit/server/dto/member/KakaoUserInfoResponseDto.java
  src/main/java/com/recordit/server/dto/member/LoginRequestDto.java
  src/main/java/com/recordit/server/dto/member/RegisterRequestDto.java
  src/main/java/com/recordit/server/dto/member/RegisterSessionResponseDto.java
  src/main/java/com/recordit/server/dto/record/RecordDetailResponseDto.java
  src/main/java/com/recordit/server/dto/record/WriteRecordRequestDto.java
  src/main/java/com/recordit/server/dto/record/WriteRecordResponseDto.java
  src/main/java/com/recordit/server/dto/record/category/RecordCategoryResponseDto.java
Labels: 🔨 Refactor

#98 [BE-157] fix: oauth dto 스네이크 케이스로 변경
  src/main/java/com/recordit/server/dto/member/GoogleAccessTokenResponseDto.java
  src/main/java/com/recordit/server/dto/member/GoogleUserInfoResponseDto.java
  src/main/java/com/recordit/server/dto/member/KakaoAccessTokenResponseDto.java
  src/main/java/com/recordit/server/dto/member/KakaoUserInfoResponseDto.java
Labels: 🐞 Bug, 🔨 Refactor

#99 [BE-158] /auth swagger 등록
  src/main/java/com/recordit/server/controller/MemberController.java
Labels: 📃 Docs

#100 [BE-130] 댓글 조회
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/dto/comment/CommentDto.java
  src/main/java/com/recordit/server/dto/comment/CommentRequestDto.java
  src/main/java/com/recordit/server/dto/comment/CommentResponseDto.java
  src/main/java/com/recordit/server/exception/comment/CommentExceptionHandler.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: 📃 Docs, ✨ Feature, ✅ Test

#102 [BE-164] 첨부 파일 null로 받을 수 있도록 변경
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/main/java/com/recordit/server/service/ImageFileService.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#103 [BE-160] 회원가입 후에 RegisterSession 지우는 로직 추가
  src/main/java/com/recordit/server/service/MemberService.java
  src/main/java/com/recordit/server/util/RedisManager.java
Labels: ✨ Feature, 🔨 Refactor

#105 [BE-165] 댓글 조회시 Body가 아닌 Parameter로 받도록 변경
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/dto/comment/CommentRequestDto.java
Labels: 🐞 Bug

#106 [BE-155] 이미지 크기 제한 변경
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 🛠 Settings

#107 [BE-163] writeRecord files를 attachments로 네이밍 변경
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🔨 Refactor

#108 [BE-167] validation 실패 시 ErrorMessage 변경
  src/main/java/com/recordit/server/exception/ErrorMessage.java
  src/main/java/com/recordit/server/exception/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#109 [BE-169] 상용 서버 Swagger UnEnabled
  src/main/resources/application-prod.yml
Labels: 🛠 Settings

#110 [BE-168] HTTPLogFilter에서 body값 출력 안되던 문제
  src/main/java/com/recordit/server/logger/HTTPLogFilter.java
Labels: 🐞 Bug

#111 [BE-170] 정책 변경으로 인한 WriteRecordRequestDto title Size 12로 변경
  src/main/java/com/recordit/server/dto/record/WriteRecordRequestDto.java
Labels: 🐞 Bug

#113 [BE-172] RecrodService에 레코드 작성 및 상세조회 리팩토링
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🔨 Refactor

#114 [BE-115] feat: 레코드 삭제
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/exception/record/NotMatchLoginUserWithRecordWriterException.java
  src/main/java/com/recordit/server/exception/record/RecordExceptionHandler.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature

#117 [BE-174] fix: 레코드 삭제와 마이레코드 병합 중 conflict 발생하여 수정
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🐞 Bug

#118 [BE-175] fix: 추억레코드 Swagger 응답 객체 올바르게 변경
  src/main/java/com/recordit/server/controller/RecordController.java
Labels: 🐞 Bug

#121 [BE-177] RecordExceptionHandler에 응답 코드 버그 수정
  src/main/java/com/recordit/server/exception/record/RecordExceptionHandler.java
Labels: 🐞 Bug

#120 [BE-129] 댓글 삭제
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/exception/comment/CommentExceptionHandler.java
  src/main/java/com/recordit/server/exception/comment/NotMatchCommentWriterException.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: ✨ Feature, ✅ Test

#119 [BE-148] 마이레코드에서 지정한 날짜로 레코드를 조회하는 기능 개발
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/dto/record/RecordByDateDto.java
  src/main/java/com/recordit/server/dto/record/RecordByDateRequestDto.java
  src/main/java/com/recordit/server/dto/record/RecordByDateResponseDto.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/main/java/com/recordit/server/util/DateTimeUtil.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#122 [BE-176] 추억 레코드 조회 기능 리팩토링
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/domain/Comment.java
  src/main/java/com/recordit/server/dto/record/MemoryRecordResponseDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordCommentDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordRequestDto.java
  src/main/java/com/recordit/server/dto/record/memory/MemoryRecordResponseDto.java
  src/main/java/com/recordit/server/repository/CommentRepository.java
  src/main/java/com/recordit/server/repository/RecordRepository.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/main/java/com/recordit/server/util/DateTimeUtil.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#123 [BE-117] 레코드 수정
  src/main/java/com/recordit/server/controller/RecordController.java
  src/main/java/com/recordit/server/domain/Record.java
  src/main/java/com/recordit/server/dto/record/ModifyRecordRequestDto.java
  src/main/java/com/recordit/server/repository/ImageFileRepository.java
  src/main/java/com/recordit/server/service/ImageFileService.java
  src/main/java/com/recordit/server/service/RecordService.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: ✨ Feature, ✅ Test

#124 [BE-178] fix: 레코드 작성 시 title validation message 수정
  src/main/java/com/recordit/server/dto/record/WriteRecordRequestDto.java
Labels: 🐞 Bug

#125 [BE-111] 레코드 카테고리 저장
  src/main/java/com/recordit/server/controller/RecordCategoryController.java
  src/main/java/com/recordit/server/dto/record/category/SaveRecordCategoryRequestDto.java
  src/main/java/com/recordit/server/exception/record/RecordExceptionHandler.java
  src/main/java/com/recordit/server/exception/record/category/HaveParentRecordCategoryException.java
  src/main/java/com/recordit/server/exception/record/category/RecordCategoryExceptionHandler.java
  src/main/java/com/recordit/server/service/RecordCategoryService.java
  src/test/java/com/recordit/server/service/RecordCategoryServiceTest.java
Labels: ✨ Feature, ✅ Test

#126 [BE-180] 레코드 수정 시 title 수정 불가능 정책에 따라 변경
  src/main/java/com/recordit/server/domain/Record.java
  src/main/java/com/recordit/server/dto/record/ModifyRecordRequestDto.java
  src/test/java/com/recordit/server/service/RecordServiceTest.java
Labels: 🐞 Bug

#127 [BE-131] 댓글 수정
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/domain/Comment.java
  src/main/java/com/recordit/server/dto/comment/ModifyCommentRequestDto.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: ✨ Feature, ✅ Test

#128 [BE-181] 댓글 삭제 시 익명 댓글을 레코드 작성자가 삭제 가능하도록 변경
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/dto/comment/DeleteCommentRequestDto.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: 🐞 Bug, ✅ Test

#130 [BE-183] fix: 레코드 삭제와 댓글 삭제 시 이미지 지우는 코드 추가
  src/main/java/com/recordit/server/service/CommentService.java
  src/main/java/com/recordit/server/service/ImageFileService.java
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🐞 Bug

#129 [BE-185] 비회원 댓글은 수정 불가능 하도록 변경
  src/main/java/com/recordit/server/exception/comment/CommentExceptionHandler.java
  src/main/java/com/recordit/server/exception/comment/NotAllowedModifyWhenNonMemberException.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: 🐞 Bug, ✅ Test

#131 [BE-184] 댓글 작성 시 댓글 내용이 있을때만 작성되도록 변경
  src/main/java/com/recordit/server/dto/comment/WriteCommentRequestDto.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/main/java/com/recordit/server/service/RecordService.java
Labels: 🐞 Bug

#132 [BE-186] 댓글 삭제 시 RequestBody로 받는 값 RequestParam으로 변경
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/dto/comment/DeleteCommentRequestDto.java
  src/main/java/com/recordit/server/dto/comment/ModifyCommentRequestDto.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: 🐞 Bug

#133 [BE-187] 댓글 수정 시 파일 단 건으로 받도록 수정
  src/main/java/com/recordit/server/controller/CommentController.java
  src/main/java/com/recordit/server/service/CommentService.java
  src/test/java/com/recordit/server/service/CommentServiceTest.java
Labels: 🐞 Bug

#135 [BE-188] refactor : 추억레코드 조회시 오늘 날짜의 레코드도 조회되도록 변경
  src/main/java/com/recordit/server/repository/RecordRepository.java
Labels: 🔨 Refactor

#136 [BE-189] 서버 모니터링을 위한 actuator prometheus 설정
  build.gradle
  src/main/java/com/recordit/server/configuration/SwaggerConfiguration.java
  src/main/java/com/recordit/server/logger/HTTPLogFilter.java
  src/main/resources/application-actuator.yml
  src/main/resources/application.yml
Labels: ✨ Feature, 🛠 Settings

#137 [BE-190] LogFilter에서 prometheus log 제거
  src/main/java/com/recordit/server/logger/HTTPLogFilter.java
Labels: 🛠 Settings

#138 [BE-191] 0.0.1에서 0.1.0으로 버전 업
  build.gradle
Labels: 🛠 Settings
